### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by neiloneill**
## 🎯 Objective

_Note why you're making this change and any relevant issues_

To complete the assignment lol

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

Added the recipe

## 👥 Who needs to review this Pull Request? 

@yl1250 @alindbloom @tommasodvc @ShogoYakame

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by yl1250** [comment]
Don't forget we need at least two approvers before merging the pull request

**Review by yl1250 — COMMENTED** [review]
I have added a step 2 and step 5 to this recipe! We can't forget the pasta water 😄

**Review by alindbloom — APPROVED** [review]
Great addition of including boiling the water and adding parmesan cheese to the pasta. This could have been a disastrous outcome.

**Review by alindbloom — APPROVED** [review]
Incorporating a modest portion of the pasta water into the pesto sauce is a stroke of culinary brilliance – it's the hidden gem that elevates the flavors!

**Review by ShogoYakame — APPROVED** [review]
I love pasta!! looks great recipe!

**Comment by yl1250** [comment]
approved!

**Pull request merged**
